### ISSUE TITLE
Spec text editor signoff?

### ISSUE THREAD

**Issue by ljharb** [ljharb/proposal-string-pad-left-right#13]
@bterlson, you're up :-) the designated reviewers have signed off in #11.

Can you review the spec text? I'd love to shoot for stage 3 at the November meeting.

**Comment by bterlson** [comment]
Feedback the first: move this repo to tc39. Once your proposal is stage 1 it's time to move to tc39 for archival purposes.

**Comment by bterlson** [comment]
> 1. If F is the empty String, let F be a string consisting of " " (a string consisting of U+0020 SPACE).

I wouldn't even bother with `" "` and just say...
1. If F is the empty String, let F be a string consisting solely of the code unit U+0020 (SPACE).

**Comment by bterlson** [comment]
> 8.If fillString is undefined, let F be the empty String.

I find F to be a very confusing name here since F is typically a function.

> 1. Repeat, while the length of F is less than fillLen: 

ECMASpeak Syntax Error: unexpected colon (delete it)

Step 13 also seems way more complex than it needs to be. It seems like you're trying to optimize your spec text, but the result is it's harder to understand. I would suggest just doing a naïve repeated concatenation rather than this doubling algorithm you have now. Something like:

```
13. Repeat, while the length of F is less than fillLen
  a. Let F be a new String value computed by concatenating F and coercedFillString.
```

Seems fine to me.

> The length property...

Delete this (sorry :-P)

Apply this feedback to padRight as well and I think this is good.

**Comment by ljharb** [comment]
Thanks! I'll update with your feedback.

Regarding step 13, this was @michaelficarra's suggestion in https://github.com/ljharb/proposal-string-pad-left-right/issues/11#issuecomment-148112061 - I can certainly revert it to use the more naive algorithm.

**Comment by michaelficarra** [comment]
@bterlson In my opinion, the current spec text is simpler and easier to understand than it was when it used your suggested algorithm.

**Comment by bterlson** [comment]
It still feels like it's giving too much implementation detail to me. How about replacing steps 13 and 14 with:

> Let _truncatedStringFiller_ be a new String value consisting of repeated concatenations of _F_ truncated to length _fillLen_.

**Comment by ljharb** [comment]
Thanks @bterlson! All of your feedback has been incorporated. Please let me know if there's anything else I can improve - otherwise, can this be considered signed off on?

**Comment by ljharb** [comment]
This has been officially signed off, and is now at stage 3!
