### ISSUE TITLE
Why not just String#pad ?

### ISSUE THREAD

**Issue by medikoo** [ljharb/proposal-string-pad-left-right#19]
We can then by _sign_ of passed `maxLength` decide on wether `left` or `right` pad should be done:

``` javascript
If (maxLength >= 0) {
  padLeft(..)
} else {
  padRight(...)
}
```

Or do you feel it'll be too confusing, and making it not on pair with `trim`, `trimLeft`, `trimRight` raises real concern (?)

**Comment by ljharb** [comment]
This decision was made by the committee - `trimLeft` and `trimLeft` are legacy names and will be available in the future as `trimStart` and `trimEnd`, which parallel with `startsWith` and `endsWith` as well.

In general, it's preferable imo and less error-prone to have two methods rather than one that's overloaded based on the sign of the argument.

Given that this proposal is in stage 3, the only remaining changes to it will be because of web compatibility, or engine implementation issues - the names and API are basically frozen.
